release 3.1
scipion-em/scipion-em-relion pull request #272
Opened 2021-02-11 23:25 UTC by azazellochg

2021-03-03 22:58 UTC, azazellochg commented
Import / convert old star files to be checked

2021-03-04 15:32 UTC, azazellochg commented
@delarosatrevin https://github.com/scipion-em/scipion-em-relion/pull/272/commits/4c3e3c0a4f63a5fe63a484f2b7f00244e204fb24 requires your closer look :)

2021-03-07 17:28 UTC, azazellochg commented
EER needs more testing and some discussion w @pconesa and @delarosatrevin

2021-03-08 08:31 UTC, pconesa commented
> EER needs more testing and some discussion w @pconesa and @delarosatrevin

Let me know how can I help.

2021-03-08 12:31 UTC, delarosatrevin requested changes
All tests (except MultiBody) are passing. Just a minor comment

2021-03-08 12:31 UTC, delarosatrevin commented on setup.py
> -       'relion': ['relion_logo.png', 'protocols.conf', 'convert/mtfs/*.star'],
Relion logo file is still a png file.

2021-03-08 14:36 UTC, azazellochg commented on setup.py
> -       'relion': ['relion_logo.png', 'protocols.conf', 'convert/mtfs/*.star'],
I have uploaded a new jpg logo

2021-03-13 18:48 UTC, azazellochg commented
I'm merging this as no comments were raised.

2021-03-13 18:48 UTC, merged